const STORE_KEY='healthPatternLog_v1';
const symptoms=['Dizziness','Lightheadedness','Palpitations','Sweating/temperature','Nausea','Weakness','Numbness/tingling','Headache/migraine','Brain fog','Hand weakness','Foot pain','Muscle spasms','Sound sensitivity','Light sensitivity'];
const contexts=['Home-cooked / standard','Fruit / vegetables','High protein','Whole grains / high fiber','Restaurant / takeout','Fried food','High added sugar','Dessert / treat','Low appetite','Skipped meal'];
const defaultMeds=[
 {id:uid(),name:'Levothyroxine',dose:'',type:'scheduled',schedule:'Daily'},
 {id:uid(),name:'Adderall',dose:'',type:'scheduled',schedule:'Daily'},
 {id:uid(),name:'Lyrica',dose:'',type:'scheduled',schedule:'Daily'},
 {id:uid(),name:'Allergy medication',dose:'',type:'scheduled',schedule:'Daily'},
 {id:uid(),name:'Viibryd',dose:'',type:'scheduled',schedule:'Daily'},
 {id:uid(),name:'Metformin',dose:'',type:'scheduled',schedule:'Daily'},
 {id:uid(),name:'Tramadol',dose:'',type:'prn',schedule:'As needed'},
 {id:uid(),name:'Methocarbamol',dose:'',type:'prn',schedule:'As needed'},
 {id:uid(),name:'Risperidone',dose:'',type:'prn',schedule:'As needed'}
];
let data=load();
function uid(){return Math.random().toString(36).slice(2,10)+Date.now().toString(36).slice(-5)}
function load(){try{let d=JSON.parse(localStorage.getItem(STORE_KEY));if(d)return d}catch(e){}return {medications:defaultMeds,logs:[],changes:[]}}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(data))}
function ensureDefaults(){const wanted=defaultMeds; wanted.forEach(w=>{if(!data.medications.some(m=>m.name.toLowerCase()===w.name.toLowerCase())) data.medications.push(w)}); const old=data.medications.find(m=>m.name==='Gabapentin / Lyrica'); if(old && !old.dose && old.schedule==='Update to current medication/dose') data.medications=data.medications.filter(m=>m!==old); save()}
function nowISO(){return new Date().toISOString()}
function localDate(iso=nowISO()){let d=new Date(iso);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function fmtTime(iso){return new Date(iso).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}
function fmtDate(iso){return new Date(iso).toLocaleDateString([], {month:'short',day:'numeric',year:'numeric'})}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function showToast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),1800)}

function makeChips(container,items){container.innerHTML='';items.forEach(x=>{let b=document.createElement('button');b.type='button';b.className='chip';b.textContent=x;b.onclick=()=>b.classList.toggle('selected');container.appendChild(b)})}
function selectedChips(container){return [...container.querySelectorAll('.chip.selected')].map(x=>x.textContent)}

function init(){
 ensureDefaults();
 todayDate.textContent=new Date().toLocaleDateString([], {weekday:'long',month:'long',day:'numeric'});
 makeChips(symptomChips,symptoms);makeChips(mealChips,contexts);makeChips(badDaySymptoms,['Dizzy','Weak','Nauseated','Headache','Numb/tingly','Overheated','Brain fog','Pain flare']);
 document.querySelectorAll('.number-scale').forEach(makeNumberScale);
 document.querySelectorAll('.top-nav button').forEach(b=>b.onclick=()=>navigate(b.dataset.page));
 document.getElementById('saveQuickLog').onclick=handleQuickLog;
 document.getElementById('saveActivity').onclick=handleActivity;
 document.getElementById('saveMeal').onclick=handleMealLog;
 document.getElementById('saveWater').onclick=handleWaterLog;
 document.getElementById('startSleep').onclick=startSleepSession;
 document.getElementById('awakeSleep').onclick=markAwake;
 document.getElementById('backToSleep').onclick=markBackToSleep;
 document.getElementById('endSleep').onclick=endSleepSession;
 badDayBtn.onclick=()=>badDayDialog.showModal(); saveBadDay.onclick=saveBadDayLog; addMedBtn.onclick=()=>openMed(); saveMed.onclick=saveMedEntry;
 trendRange.onchange=renderTrends; reportRange.onchange=renderDoctor; printReport.onclick=()=>window.print(); exportJson.onclick=exportJSON; exportCsv.onclick=exportCSV;
 document.querySelectorAll('.med-filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.med-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMedTable(b.dataset.filter)});
 renderAll(); if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./sw.js').catch(()=>{});
}
function makeNumberScale(container){const input=document.getElementById(container.dataset.target);for(let n=1;n<=10;n++){let b=document.createElement('button');b.type='button';b.textContent=n;b.className='scale-btn'+(+input.value===n?' selected':'');b.onclick=()=>{input.value=n;container.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b))};container.appendChild(b)}}
function bindRange(id,out){let i=document.getElementById(id),o=document.getElementById(out);i.oninput=()=>o.textContent=i.value}
function navigate(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));document.querySelectorAll('.top-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='trends')renderTrends();if(page==='doctor')renderDoctor();window.scrollTo({top:0,behavior:'smooth'})}

function handleQuickLog(){let ts=nowISO();data.logs.push({id:uid(),kind:'symptom',timestamp:ts,pain:+pain.value,fatigue:+fatigue.value,fog:+fog.value,symptoms:selectedChips(symptomChips),notes:quickNotes.value.trim()});save();quickNotes.value='';document.querySelectorAll('#symptomChips .selected').forEach(x=>x.classList.remove('selected'));renderAll();showToast('Symptom check-in saved')}
function handleActivity(){if(!steps.value&&!activityText.value.trim()){showToast('Add steps or an activity description first');return}data.logs.push({id:uid(),kind:'activity',timestamp:nowISO(),steps:steps.value?+steps.value:null,activity:activityText.value.trim()});save();steps.value='';activityText.value='';renderAll();showToast('Activity saved')}
function handleMealLog(){if(!mealText.value.trim()&&!selectedChips(mealChips).length){showToast('Add a meal or tag first');return}data.logs.push({id:uid(),kind:'meal',timestamp:nowISO(),meal:mealText.value.trim(),contexts:selectedChips(mealChips)});save();mealText.value='';document.querySelectorAll('#mealChips .selected').forEach(x=>x.classList.remove('selected'));renderAll();showToast('Meal saved')}
function sleepSession(){return data.sleepSession||null}
function startSleepSession(){if(sleepSession()){showToast('A sleep session is already in progress');return}data.sleepSession={start:nowISO(),awakeSince:null,disturbances:[]};save();renderSleepTracker();showToast('Sleep started')}
function markAwake(){let s=sleepSession();if(!s){showToast('Start sleep first');return}if(s.awakeSince){showToast('Already marked awake');return}s.awakeSince=nowISO();save();renderSleepTracker();showToast('Awake time started')}
function markBackToSleep(){let s=sleepSession();if(!s){showToast('Start sleep first');return}if(!s.awakeSince){showToast('Mark Awake first');return}let end=nowISO();s.disturbances.push({start:s.awakeSince,end});s.awakeSince=null;save();renderSleepTracker();showToast('Back to sleep logged')}
function endSleepSession(){let s=sleepSession();if(!s){showToast('No sleep session in progress');return}let end=nowISO();if(s.awakeSince){s.disturbances.push({start:s.awakeSince,end});s.awakeSince=null}let timeInBedMs=Math.max(0,new Date(end)-new Date(s.start));let awakeMs=s.disturbances.reduce((n,d)=>n+Math.max(0,new Date(d.end)-new Date(d.start)),0);let sleepMs=Math.max(0,timeInBedMs-awakeMs);data.logs.push({id:uid(),kind:'sleep',timestamp:end,start:s.start,end,disturbances:s.disturbances,timeInBedHours:timeInBedMs/3600000,awakeMinutes:Math.round(awakeMs/60000),hours:sleepMs/3600000,quality:+sleepQuality.value,notes:sleepNotes.value.trim()});data.sleepSession=null;save();sleepNotes.value='';renderAll();showToast('Sleep session saved')}
function durationText(ms){let mins=Math.max(0,Math.round(ms/60000)),h=Math.floor(mins/60),m=mins%60;return h?`${h}h ${m}m`:`${m}m`}
function renderSleepTracker(){let s=sleepSession();if(!s){sleepStatus.innerHTML='No sleep session in progress.';sleepDisturbances.innerHTML='';startSleep.disabled=false;awakeSleep.disabled=true;backToSleep.disabled=true;endSleep.disabled=true;return}let state=s.awakeSince?`Awake since ${fmtTime(s.awakeSince)}`:`Sleeping since ${fmtTime(s.start)}`;sleepStatus.innerHTML=`<strong>${state}</strong>`;let ds=s.disturbances||[];sleepDisturbances.innerHTML=ds.length?ds.map((d,i)=>`<div class="timeline-item"><strong>Disturbance ${i+1}</strong><div class="med-meta">${fmtTime(d.start)}–${fmtTime(d.end)} • ${durationText(new Date(d.end)-new Date(d.start))}</div></div>`).join(''):'';startSleep.disabled=true;awakeSleep.disabled=!!s.awakeSince;backToSleep.disabled=!s.awakeSince;endSleep.disabled=false}
function handleWaterLog(){if(!waterOz.value){showToast('Enter ounces first');return}data.logs.push({id:uid(),kind:'water',timestamp:nowISO(),ounces:+waterOz.value,flavoring:waterFlavor.checked,hydrationSalts:waterSalts.checked});save();waterOz.value='';waterFlavor.checked=false;waterSalts.checked=false;renderAll();showToast('Water saved')}
function saveBadDayLog(e){e.preventDefault();data.logs.push({id:uid(),kind:'symptom',timestamp:nowISO(),pain:+bdPain.value,fatigue:+bdFatigue.value,fog:null,symptoms:selectedChips(badDaySymptoms),notes:`Function: ${badDayFunction.value}${badDayNote.value.trim()?'. '+badDayNote.value.trim():''}`,badDay:true});save();badDayNote.value='';document.querySelectorAll('#badDaySymptoms .selected').forEach(x=>x.classList.remove('selected'));badDayDialog.close();renderAll();showToast('Bad day log saved')}
function logMed(id){let med=data.medications.find(m=>m.id===id);if(!med)return;data.logs.push({id:uid(),kind:'medication',timestamp:nowISO(),medId:id,name:med.name,dose:med.dose,type:med.type});save();renderAll();showToast(`${med.name} logged`)}

function openMed(id){let m=id?data.medications.find(x=>x.id===id):null;medDialogTitle.textContent=m?'Edit medication':'Add medication';medId.value=m?.id||'';medName.value=m?.name||'';medDose.value=m?.dose||'';medType.value=m?.type||'scheduled';medSchedule.value=m?.schedule||'';medDialog.showModal()}
function saveMedEntry(e){e.preventDefault();if(!medName.value.trim())return;let obj={id:medId.value||uid(),name:medName.value.trim(),dose:medDose.value.trim(),type:medType.value,schedule:medSchedule.value.trim()};let idx=data.medications.findIndex(x=>x.id===obj.id);if(idx>=0)data.medications[idx]=obj;else data.medications.push(obj);save();medDialog.close();renderAll();showToast('Medication saved')}
function deleteMed(id){if(!confirm('Remove this medication from the active list? Existing logged doses will remain in your history.'))return;data.medications=data.medications.filter(m=>m.id!==id);save();renderAll()}
function renderAll(){renderMedTable();renderMedHistory();renderSleepTracker();renderTimeline();renderTrends();renderDoctor()}
function renderMedTable(filter=document.querySelector('.med-filter.active')?.dataset.filter||'scheduled'){medTable.innerHTML='';data.medications.filter(m=>m.type===filter).forEach(m=>{let r=document.createElement('div');r.className='med-table-row';r.innerHTML=`<div><strong>${esc(m.name)}</strong><div class="med-meta">${esc(m.type)}</div></div><div>${esc(m.dose||'—')}</div><div class="schedule med-meta">${esc(m.schedule||'—')}</div><div class="row"><button class="primary small take">Take</button><button class="secondary small edit">Edit</button><button class="secondary small del">×</button></div>`;r.querySelector('.take').onclick=()=>logMed(m.id);r.querySelector('.edit').onclick=()=>openMed(m.id);r.querySelector('.del').onclick=()=>deleteMed(m.id);medTable.appendChild(r)})}
function renderMedHistory(){let logs=data.logs.filter(l=>l.kind==='medication').sort((a,b)=>b.timestamp.localeCompare(a.timestamp));medHistory.innerHTML=logs.length?'':'<p>No medications logged yet.</p>';logs.forEach(l=>medHistory.insertAdjacentHTML('beforeend',`<div class="timeline-item"><div class="timeline-time">${fmtDate(l.timestamp)} • ${fmtTime(l.timestamp)}</div><strong>${esc(l.name)}</strong>${l.dose?` <span class="med-meta">${esc(l.dose)}</span>`:''}</div>`))}
function renderTimeline(){let t=localDate();let logs=data.logs.filter(l=>localDate(l.timestamp)===t&&l.kind!=='medication').sort((a,b)=>b.timestamp.localeCompare(a.timestamp));todayTimeline.innerHTML=logs.length?'':'<p>No entries yet today.</p>';logs.forEach(l=>{let text='';if(l.kind==='symptom')text=`<strong>${l.badDay?'Bad day log':'Symptom check-in'}</strong><div class="med-meta">Pain ${l.pain ?? '—'}/10 • Fatigue ${l.fatigue ?? '—'}/10${l.symptoms?.length?' • '+esc(l.symptoms.join(', ')):''}</div>${l.notes?`<p>${esc(l.notes)}</p>`:''}`;if(l.kind==='activity')text=`<strong>Activity</strong><div class="med-meta">${l.steps!=null?l.steps+' steps':''}${l.steps!=null&&l.activity?' • ':''}${esc(l.activity||'')}</div>`;if(l.kind==='meal')text=`<strong>Meal</strong><div class="med-meta">${esc(l.meal||'')}${l.contexts?.length?' • '+esc(l.contexts.join(', ')):''}</div>`;if(l.kind==='sleep')text=`<strong>Sleep</strong><div class="med-meta">${l.hours!=null?l.hours.toFixed(1)+' hr estimated sleep':''}${l.disturbances?` • ${l.disturbances.length} disturbance(s) • ${l.awakeMinutes||0} min awake`:''}${l.quality?` • quality ${esc(l.quality)}/10`:''}${l.notes?' • '+esc(l.notes):''}</div>`;if(l.kind==='water')text=`<strong>Water</strong><div class="med-meta">${l.ounces} oz${l.flavoring?' • flavoring':''}${l.hydrationSalts?' • hydration salts':''}</div>`;todayTimeline.insertAdjacentHTML('beforeend',`<div class="timeline-item"><div class="timeline-time">${fmtTime(l.timestamp)}</div>${text}</div>`)})}

function withinDays(log,n){if(n==='all')return true;return new Date(log.timestamp)>=new Date(Date.now()-Number(n)*86400000)}
function avg(arr){let a=arr.filter(v=>Number.isFinite(v));return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
function symptomLogs(range){return data.logs.filter(l=>l.kind==='symptom'&&withinDays(l,range))}
function activityLogs(range){return data.logs.filter(l=>l.kind==='activity'&&withinDays(l,range))}
function dailyAggregate(range){let map={};data.logs.filter(l=>withinDays(l,range)).forEach(l=>{let d=localDate(l.timestamp);map[d]??={date:d,pain:[],fatigue:[],fog:[],steps:0};if(l.kind==='symptom'){if(Number.isFinite(l.pain))map[d].pain.push(l.pain);if(Number.isFinite(l.fatigue))map[d].fatigue.push(l.fatigue);if(Number.isFinite(l.fog))map[d].fog.push(l.fog)}if(l.kind==='activity'&&l.steps)map[d].steps=Math.max(map[d].steps,l.steps)});return Object.values(map).sort((a,b)=>a.date.localeCompare(b.date)).map(x=>({...x,pain:avg(x.pain),fatigue:avg(x.fatigue),fog:avg(x.fog)}))}
function renderTrends(){let range=trendRange.value,daily=dailyAggregate(range);drawLineChart(symptomChart,daily,[['pain','Pain'],['fatigue','Fatigue'],['fog','Brain fog']],10);drawLineChart(activityChart,daily,[['steps','Steps']],null);renderSymptomFrequency(range);renderCorrelation(range)}
function drawLineChart(canvas,rows,series,maxY){let ratio=devicePixelRatio||1,w=canvas.clientWidth||700,h=180;canvas.width=w*ratio;canvas.height=h*ratio;let c=canvas.getContext('2d');c.scale(ratio,ratio);c.clearRect(0,0,w,h);c.strokeStyle='#e5e1ef';c.lineWidth=1;for(let i=0;i<5;i++){let y=15+i*(h-35)/4;c.beginPath();c.moveTo(36,y);c.lineTo(w-8,y);c.stroke()}if(!rows.length){c.fillStyle='#6d6980';c.font='13px sans-serif';c.fillText('No data yet',45,95);return}let vals=[];series.forEach(([k])=>rows.forEach(r=>{if(Number.isFinite(r[k]))vals.push(r[k])}));let ymax=maxY||Math.max(...vals,1)*1.1,ymin=0;const palette=['#6f5bd3','#b94b67','#2d8f7b'];series.forEach(([k,label],si)=>{c.strokeStyle=palette[si%palette.length];c.fillStyle=palette[si%palette.length];c.lineWidth=2;c.beginPath();let started=false;rows.forEach((r,i)=>{if(!Number.isFinite(r[k]))return;let x=40+(rows.length===1?0:i/(rows.length-1))*(w-55);let y=h-25-((r[k]-ymin)/(ymax-ymin||1))*(h-45);started?c.lineTo(x,y):c.moveTo(x,y);started=true});c.stroke();c.fillRect(42+si*100,5,10,3);c.fillStyle='#504c67';c.font='11px sans-serif';c.fillText(label,56+si*100,10)});c.fillStyle='#6d6980';c.font='10px sans-serif';c.fillText(rows[0].date.slice(5),38,h-8);if(rows.length>1)c.fillText(rows.at(-1).date.slice(5),w-42,h-8)}
function renderSymptomFrequency(range){let counts={};symptomLogs(range).forEach(l=>(l.symptoms||[]).forEach(s=>counts[s]=(counts[s]||0)+1));let entries=Object.entries(counts).sort((a,b)=>b[1]-a[1]);let max=entries[0]?.[1]||1;symptomFrequency.innerHTML=entries.length?'':'<p>No symptom tags logged yet.</p>';entries.forEach(([s,n])=>symptomFrequency.insertAdjacentHTML('beforeend',`<div class="bar-row"><span>${esc(s)}</span><div class="bar-track"><div class="bar-fill" style="width:${n/max*100}%"></div></div><strong>${n}</strong></div>`))}
function renderCorrelation(range){let medLogs=data.logs.filter(l=>l.kind==='medication'&&withinDays(l,range));let sLogs=symptomLogs(range);let groups={};medLogs.forEach(m=>{let mt=new Date(m.timestamp).getTime();let after=sLogs.filter(s=>{let dt=new Date(s.timestamp).getTime()-mt;return dt>=0&&dt<=6*3600000});let g=groups[m.name]??={n:0,pain:[],fatigue:[],symptoms:{}};g.n++;after.forEach(s=>{if(Number.isFinite(s.pain))g.pain.push(s.pain);if(Number.isFinite(s.fatigue))g.fatigue.push(s.fatigue);(s.symptoms||[]).forEach(x=>g.symptoms[x]=(g.symptoms[x]||0)+1)});groups[m.name]=g});let entries=Object.entries(groups);medCorrelation.innerHTML=entries.length?'':'<p>No medication doses logged in this period yet.</p>';entries.forEach(([name,g])=>{let top=Object.entries(g.symptoms).sort((a,b)=>b[1]-a[1]).slice(0,3).map(x=>x[0]).join(', ')||'none logged';medCorrelation.insertAdjacentHTML('beforeend',`<div class="timeline-item"><strong>${esc(name)}</strong><div class="med-meta">${g.n} dose log(s) • avg pain within 6h: ${avg(g.pain)?.toFixed(1)??'—'} • avg fatigue: ${avg(g.fatigue)?.toFixed(1)??'—'}</div><p>Most common tags within 6h: ${esc(top)}</p></div>`)})}

function renderDoctor(){let range=reportRange.value,slogs=symptomLogs(range),alogs=activityLogs(range),mlogs=data.logs.filter(l=>l.kind==='medication'&&withinDays(l,range)),mealLogs=data.logs.filter(l=>l.kind==='meal'&&withinDays(l,range)),sleepLogs=data.logs.filter(l=>l.kind==='sleep'&&withinDays(l,range)),waterLogs=data.logs.filter(l=>l.kind==='water'&&withinDays(l,range)),daily=dailyAggregate(range);reportRangeLabel.textContent=range==='all'?'All recorded data':`Last ${range} days`;let steps=alogs.map(x=>x.steps).filter(Number.isFinite);let counts={};slogs.forEach(l=>(l.symptoms||[]).forEach(s=>counts[s]=(counts[s]||0)+1));let topSymptoms=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,8);let mealCounts={};mealLogs.forEach(l=>(l.contexts||[]).forEach(x=>mealCounts[x]=(mealCounts[x]||0)+1));let avgSleep=avg(sleepLogs.map(x=>x.hours)),totalDisturbances=sleepLogs.reduce((n,x)=>n+(x.disturbances?.length||0),0),totalAwakeMinutes=sleepLogs.reduce((n,x)=>n+(x.awakeMinutes||0),0),avgSleepQuality=avg(sleepLogs.map(x=>Number(x.quality)));let waterOz=waterLogs.reduce((n,x)=>n+(x.ounces||0),0);reportSummary.innerHTML=`
 <div class="research-box"><h3>Clinical context: triglycerides are multifactorial</h3><p>An elevated triglyceride value should be interpreted in clinical context rather than used as a stand-alone proxy for dietary intake. Current ADA guidance identifies <strong>diabetes, chronic liver disease, hypothyroidism, medications, obesity/metabolic syndrome, and lifestyle factors</strong> as contributors that should be addressed when triglycerides are elevated. The ADA also states that prediabetes is associated with dyslipidemia characterized by high triglycerides and/or low HDL, and identifies physical inactivity and metabolic dysfunction-associated steatotic liver disease (MASLD) as conditions associated with insulin resistance.</p><p class="source-note"><strong>Sources:</strong> American Diabetes Association, Standards of Care in Diabetes—2026, sections 2 and 10. <a href="https://diabetesjournals.org/care/article/49/Supplement_1/S27/163926/2-Diagnosis-and-Classification-of-Diabetes" target="_blank" rel="noopener">Diagnosis & Classification</a> · <a href="https://diabetesjournals.org/care/article/49/Supplement_1/S216/163933/10-Cardiovascular-Disease-and-Risk-Management" target="_blank" rel="noopener">Cardiovascular Risk Management</a></p><p class="muted"><strong>Purpose:</strong> This context does not establish the cause of any individual laboratory result. It documents why diet is only one part of an appropriate clinical assessment.</p></div>
 <div class="metric-grid"><div class="metric"><span>Avg pain</span><strong>${avg(slogs.map(x=>x.pain))?.toFixed(1)??'—'}</strong></div><div class="metric"><span>Avg fatigue</span><strong>${avg(slogs.map(x=>x.fatigue))?.toFixed(1)??'—'}</strong></div><div class="metric"><span>Avg brain fog</span><strong>${avg(slogs.map(x=>x.fog))?.toFixed(1)??'—'}</strong></div><div class="metric"><span>Avg steps</span><strong>${avg(steps)?.toFixed(0)??'—'}</strong></div></div>
 <h3 class="section-title">Symptoms & function</h3><p>${slogs.length} symptom check-in(s). Most frequent tags: ${topSymptoms.length?topSymptoms.map(([s,n])=>`${esc(s)} (${n})`).join(' • '):'none recorded'}.</p><p>${daily.length?`${daily.length} day(s) contain logged data.`:'No activity data recorded.'}</p><h3 class="section-title">Activity notes</h3>${alogs.length?`<table class="report-table"><tbody>${alogs.slice().sort((a,b)=>b.timestamp.localeCompare(a.timestamp)).map(a=>`<tr><td>${fmtDate(a.timestamp)}</td><td>${a.steps!=null?esc(a.steps+' steps'):''}${a.steps!=null&&a.activity?' • ':''}${esc(a.activity||'')}</td></tr>`).join('')}</tbody></table>`:'<p>No activity entries recorded in this period.</p>'}
 <h3 class="section-title">Meals: documented context</h3>${mealLogs.length?`<p>${mealLogs.length} meal entry/entries recorded. Tag counts: ${Object.entries(mealCounts).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`${esc(k)} (${v})`).join(' • ')||'no tags'}.</p>`:'<p>No meal entries recorded in this period.</p>'}
 <h3 class="section-title">Sleep & hydration</h3><p>Average estimated sleep: ${avgSleep?.toFixed(1)??'—'} hours. ${sleepLogs.length?`${totalDisturbances} recorded sleep disturbance(s), totaling ${totalAwakeMinutes} awake minute(s). Average sleep quality: ${avgSleepQuality?.toFixed(1)??'—'}/10.`:'No sleep sessions recorded.'} Water logged: ${waterOz||'—'} oz across ${waterLogs.length} entry/entries.</p>
 <h3 class="section-title">Medication use</h3><table class="report-table"><tbody>${medUseRows(mlogs)}</tbody></table>
 <h3 class="section-title">Current medications & supplements</h3><table class="report-table"><thead><tr><th>Name</th><th>Dose</th><th>Type</th><th>Schedule / notes</th></tr></thead><tbody>${data.medications.map(m=>`<tr><td>${esc(m.name)}</td><td>${esc(m.dose||'Not entered')}</td><td>${esc(m.type)}</td><td>${esc(m.schedule||'')}</td></tr>`).join('')}</tbody></table>
 <h3 class="section-title">Interpretation note</h3><p>This report summarizes self-recorded observations and timestamps. It is intended to support clinical discussion. Associations do not establish causation, and the report does not replace medical evaluation.</p>`} 
function medUseRows(logs){let c={};logs.forEach(l=>c[l.name]=(c[l.name]||0)+1);let rows=Object.entries(c).sort((a,b)=>b[1]-a[1]);return rows.length?rows.map(([n,v])=>`<tr><td>${esc(n)}</td><td>${v} logged dose(s)</td></tr>`).join(''):'<tr><td>No doses logged in this period.</td></tr>'}
function contextSummary(alogs){let c={};alogs.forEach(l=>(l.contexts||[]).forEach(x=>c[x]=(c[x]||0)+1));let a=Object.entries(c).sort((x,y)=>y[1]-x[1]);return a.length?a.map(([k,v])=>`${esc(k)} (${v})`).join(' • '):'No meal/context tags recorded.'}

function download(name,type,text){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportJSON(){download(`health-pattern-backup-${localDate()}.json`,'application/json',JSON.stringify(data,null,2));showToast('Backup exported')}
function exportCSV(){let rows=[['timestamp','kind','name','dose','pain','fatigue','brain_fog','symptoms','steps','activity','contexts','meal','sleep_start','sleep_end','estimated_sleep_hours','sleep_disturbances','awake_minutes','sleep_quality_1_10','water_oz','flavoring','hydration_salts','notes']];data.logs.slice().sort((a,b)=>a.timestamp.localeCompare(b.timestamp)).forEach(l=>rows.push([l.timestamp,l.kind,l.name||'',l.dose||'',l.pain??'',l.fatigue??'',l.fog??'',(l.symptoms||[]).join('; '),l.steps??'',l.activity||'',(l.contexts||[]).join('; '),l.meal||'',l.start||'',l.end||'',l.hours??'',l.disturbances?.length??'',l.awakeMinutes??'',l.quality||'',l.ounces??'',l.flavoring??'',l.hydrationSalts??'',l.notes||'']));let csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('\"','\"\"')+'"').join(',')).join('\n');download(`health-pattern-log-${localDate()}.csv`,'text/csv',csv);showToast('CSV exported')}

init();
